Repository TEAM-TATTOUR/tattour-server, pull requests merged in 2023-07, with the labels that each got.

#8 #6 [feat] sticker, theme, style, custom, banner 관련 Entity 추가
  server/build.gradle
  server/src/main/java/org/tattour/server/ServerApplication.java
  server/src/main/java/org/tattour/server/banner/domain/Banner.java
  server/src/main/java/org/tattour/server/custom/domain/Custom.java
  server/src/main/java/org/tattour/server/custom/domain/CustomImage.java
  server/src/main/java/org/tattour/server/custom/domain/CustomStyle.java
  server/src/main/java/org/tattour/server/custom/domain/CustomTheme.java
  server/src/main/java/org/tattour/server/discount/domain/Discount.java
  server/src/main/java/org/tattour/server/golbal/util/AuditingTimeEntity.java
  server/src/main/java/org/tattour/server/sticker/domain/Sticker.java
  server/src/main/java/org/tattour/server/sticker/domain/StickerImage.java
  server/src/main/java/org/tattour/server/sticker/domain/StickerStyle.java
  server/src/main/java/org/tattour/server/sticker/domain/StickerTheme.java
  server/src/main/java/org/tattour/server/style/domain/Style.java
  server/src/main/java/org/tattour/server/theme/domain/Theme.java
Labels: feat, 🐱서린

#10 #7 [feat] user, order, point 관련 entity 추가 및 mysql 데이터 타입 매칭에 따른 entity 수정
  server/build.gradle
  server/src/main/java/org/tattour/server/banner/domain/Banner.java
  server/src/main/java/org/tattour/server/custom/domain/Custom.java
  server/src/main/java/org/tattour/server/custom/domain/CustomImage.java
  server/src/main/java/org/tattour/server/custom/domain/CustomStyle.java
  server/src/main/java/org/tattour/server/custom/domain/CustomTheme.java
  server/src/main/java/org/tattour/server/discount/domain/Discount.java
  server/src/main/java/org/tattour/server/global/config/SecurityConfig.java
  server/src/main/java/org/tattour/server/global/config/SwaggerConfig.java
  server/src/main/java/org/tattour/server/global/config/jwt/JwtService.java
  server/src/main/java/org/tattour/server/global/dto/ApiResponse.java
  server/src/main/java/org/tattour/server/global/dto/FailResponse.java
  server/src/main/java/org/tattour/server/global/dto/SuccessResponse.java
  server/src/main/java/org/tattour/server/global/dto/SuccessType.java
  server/src/main/java/org/tattour/server/global/exception/BusinessException.java
  server/src/main/java/org/tattour/server/global/exception/ControllerExceptionHandler.java
  server/src/main/java/org/tattour/server/global/exception/ErrorType.java
  server/src/main/java/org/tattour/server/global/exception/NotFoundException.java
  server/src/main/java/org/tattour/server/global/exception/UnauthorizedException.java
  server/src/main/java/org/tattour/server/global/util/AuditingTimeEntity.java
  server/src/main/java/org/tattour/server/order/domain/Order.java
  server/src/main/java/org/tattour/server/point/domain/PointChargeRequest.java
  server/src/main/java/org/tattour/server/point/domain/UserPointLog.java
  server/src/main/java/org/tattour/server/sticker/domain/Sticker.java
  server/src/main/java/org/tattour/server/sticker/domain/StickerImage.java
  server/src/main/java/org/tattour/server/sticker/domain/StickerStyle.java
  server/src/main/java/org/tattour/server/sticker/domain/StickerTheme.java
  server/src/main/java/org/tattour/server/style/domain/Style.java
  server/src/main/java/org/tattour/server/theme/domain/Theme.java
  server/src/main/java/org/tattour/server/user/domain/PhoneNumberVerificationCode.java
  server/src/main/java/org/tattour/server/user/domain/ProductLiked.java
  server/src/main/java/org/tattour/server/user/domain/User.java
  server/src/main/java/org/tattour/server/user/domain/userShippingAddress.java
Labels: feat, 🐶 찬미

#16 #11 [feat] user api 구현 중
  server/build.gradle
  server/src/main/java/org/tattour/server/ServerApplication.java
  server/src/main/java/org/tattour/server/global/config/WebConfig.java
  server/src/main/java/org/tattour/server/global/config/jwt/JwtService.java
  server/src/main/java/org/tattour/server/global/config/resolver/UserId.java
  server/src/main/java/org/tattour/server/global/config/resolver/UserIdResolver.java
  server/src/main/java/org/tattour/server/global/dto/SuccessType.java
  server/src/main/java/org/tattour/server/global/exception/ControllerExceptionHandler.java
  server/src/main/java/org/tattour/server/global/exception/ErrorType.java
  server/src/main/java/org/tattour/server/global/util/EntityDtoMapper.java
  server/src/main/java/org/tattour/server/global/util/RandomNumberGenerator.java
  server/src/main/java/org/tattour/server/infra/sms/controller/SmsController.java
  server/src/main/java/org/tattour/server/infra/sms/controller/dto/request/PostSendCodeReq.java
  server/src/main/java/org/tattour/server/infra/sms/domain/PhoneNumberVerificationCode.java
  server/src/main/java/org/tattour/server/infra/sms/provider/PhoneNumberVerificationCodeProvider.java
  server/src/main/java/org/tattour/server/infra/sms/provider/PhoneNumberVerificationCodeProviderImpl.java
  server/src/main/java/org/tattour/server/infra/sms/repository/PhoneNumberVerificationCodeRepositoryImpl.java
  server/src/main/java/org/tattour/server/infra/sms/service/PhoneNumberVerificationCodeService.java
  server/src/main/java/org/tattour/server/infra/sms/service/PhoneNumberVerificationCodeServiceImpl.java
  server/src/main/java/org/tattour/server/infra/sms/service/SmsServiceImpl.java
  server/src/main/java/org/tattour/server/infra/sms/service/dto/request/MessageDto.java
  server/src/main/java/org/tattour/server/infra/sms/service/dto/request/SendVerificationCodeReq.java
  server/src/main/java/org/tattour/server/infra/sms/service/dto/request/SmsReq.java
  server/src/main/java/org/tattour/server/infra/sms/service/dto/response/SmsRes.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/KakaoApiClient.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/KakaoAuthApiClient.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/domain/SocialPlatform.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/dto/response/KakaoAccessTokenResponse.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/dto/response/KakaoAccount.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/dto/response/KakaoUserRes.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/service/KakaoSocialService.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/service/SocialService.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/service/SocialServiceProvider.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/service/dto/SocialLoginRequest.java
  server/src/main/java/org/tattour/server/user/controller/UserController.java
  server/src/main/java/org/tattour/server/user/controller/dto/request/GetVerifyCodeReq.java
  server/src/main/java/org/tattour/server/user/controller/dto/request/LoginReq.java
  server/src/main/java/org/tattour/server/user/controller/dto/request/PatchUserInfoReq.java
  server/src/main/java/org/tattour/server/user/controller/dto/response/GetVerifyCodeRes.java
  server/src/main/java/org/tattour/server/user/controller/dto/response/LoginRes.java
  server/src/main/java/org/tattour/server/user/domain/User.java
  server/src/main/java/org/tattour/server/user/provider/UserProvider.java
  server/src/main/java/org/tattour/server/user/provider/impl/UserProviderImpl.java
  server/src/main/java/org/tattour/server/user/repository/impl/UserRepositoryImpl.java
  server/src/main/java/org/tattour/server/user/service/ProductLikedServiceImpl.java
  server/src/main/java/org/tattour/server/user/service/UserService.java
  server/src/main/java/org/tattour/server/user/service/UserServiceImpl.java
  server/src/main/java/org/tattour/server/user/service/dto/request/AddUserInfoReq.java
  server/src/main/java/org/tattour/server/user/service/dto/request/SaveUserReq.java
  server/src/main/java/org/tattour/server/user/service/dto/request/UpdateUserInfoReq.java
  server/src/main/java/org/tattour/server/user/service/dto/response/GetUserProfileRes.java
  server/src/main/java/org/tattour/server/user/service/dto/response/UserRes.java
  server/src/main/resources/logback-spring.xml
Labels: feat, 🐶 찬미

#27 #21 [feat] ordersheet 가져오기 api
  server/src/main/java/org/tattour/server/domain/order/controller/OrderController.java
  server/src/main/java/org/tattour/server/domain/order/controller/dto/request/GetOrderSheetReq.java
  server/src/main/java/org/tattour/server/domain/order/controller/dto/response/GetOrderSheetRes.java
  server/src/main/java/org/tattour/server/domain/order/provider/OrderProvider.java
  server/src/main/java/org/tattour/server/domain/order/provider/dto/response/GetOrderAmountRes.java
  server/src/main/java/org/tattour/server/domain/order/provider/dto/response/GetUserOrderHistoryListRes.java
  server/src/main/java/org/tattour/server/domain/order/provider/dto/response/GetUserOrderPointRes.java
  server/src/main/java/org/tattour/server/domain/order/provider/impl/OrderProviderImpl.java
  server/src/main/java/org/tattour/server/domain/order/repository/OrderRepository.java
  server/src/main/java/org/tattour/server/domain/order/repository/impl/OrderRepositoryImpl.java
  server/src/main/java/org/tattour/server/domain/order/service/OrderService.java
  server/src/main/java/org/tattour/server/domain/order/service/dto/request/PostOrderReq.java
  server/src/main/java/org/tattour/server/domain/order/service/dto/response/PostOrderRes.java
  server/src/main/java/org/tattour/server/domain/order/service/impl/OrderServiceImpl.java
  server/src/main/java/org/tattour/server/domain/sticker/provider/StickerProvider.java
  server/src/main/java/org/tattour/server/domain/sticker/provider/dto/response/GetOrderSheetStickerInfo.java
  server/src/main/java/org/tattour/server/domain/sticker/provider/impl/StickerProviderImpl.java
  server/src/main/java/org/tattour/server/domain/user/service/ProductLikedService.java
  server/src/main/java/org/tattour/server/domain/user/service/UserService.java
  server/src/main/java/org/tattour/server/domain/user/service/impl/ProductLikedServiceImpl.java
  server/src/main/java/org/tattour/server/domain/user/service/impl/UserServiceImpl.java
  server/src/main/java/org/tattour/server/global/exception/ControllerExceptionHandler.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/service/KakaoSocialService.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/service/SocialService.java
  server/src/main/resources/logback-spring.xml
Labels: feat, 🐶 찬미

#28 #15 [feat] custom,theme,style api 추가
  server/src/main/java/org/tattour/server/domain/custom/controller/CustomController.java
  server/src/main/java/org/tattour/server/domain/custom/controller/dto/request/ApplyCustomReq.java
  server/src/main/java/org/tattour/server/domain/custom/controller/dto/request/UpdateCustomReq.java
  server/src/main/java/org/tattour/server/domain/custom/controller/dto/response/ApplyCustomRes.java
  server/src/main/java/org/tattour/server/domain/custom/controller/dto/response/UpdateCustomRes.java
  server/src/main/java/org/tattour/server/domain/custom/domain/Custom.java
  server/src/main/java/org/tattour/server/domain/custom/domain/CustomImage.java
  server/src/main/java/org/tattour/server/domain/custom/domain/CustomTheme.java
  server/src/main/java/org/tattour/server/domain/custom/exception/NotFoundCustomException.java
  server/src/main/java/org/tattour/server/domain/custom/service/CustomService.java
  server/src/main/java/org/tattour/server/domain/custom/service/CustomServiceImpl.java
  server/src/main/java/org/tattour/server/domain/custom/service/dto/request/UpdateCustomInfo.java
  server/src/main/java/org/tattour/server/domain/custom/service/dto/response/CustomInfo.java
  server/src/main/java/org/tattour/server/domain/sticker/service/dto/response/StickerSummaryListRes.java
  server/src/main/java/org/tattour/server/domain/style/controller/StyleController.java
  server/src/main/java/org/tattour/server/domain/style/service/StyleService.java
  server/src/main/java/org/tattour/server/domain/style/service/StyleServiceImpl.java
  server/src/main/java/org/tattour/server/domain/style/service/dto/response/StyleInfo.java
  server/src/main/java/org/tattour/server/domain/style/service/dto/response/StyleInfoList.java
  server/src/main/java/org/tattour/server/domain/style/service/dto/response/StyleSummary.java
  server/src/main/java/org/tattour/server/domain/style/service/dto/response/StyleSummaryList.java
  server/src/main/java/org/tattour/server/domain/theme/controller/ThemeController.java
  server/src/main/java/org/tattour/server/domain/theme/service/ThemeService.java
  server/src/main/java/org/tattour/server/domain/theme/service/ThemeServiceImpl.java
  server/src/main/java/org/tattour/server/domain/theme/service/dto/response/ThemeInfo.java
  server/src/main/java/org/tattour/server/domain/theme/service/dto/response/ThemeInfoList.java
  server/src/main/java/org/tattour/server/domain/theme/service/dto/response/ThemeSummary.java
  server/src/main/java/org/tattour/server/domain/theme/service/dto/response/ThemeSummaryList.java
  server/src/main/java/org/tattour/server/domain/user/controller/UserController.java
  server/src/main/java/org/tattour/server/domain/user/service/UserService.java
  server/src/main/java/org/tattour/server/domain/user/service/impl/UserServiceImpl.java
  server/src/main/java/org/tattour/server/global/dto/SuccessType.java
  server/src/main/java/org/tattour/server/global/exception/ErrorType.java
Labels: feat, 🐱서린

#31 #21 [feat] order
  server/src/main/java/org/tattour/server/domain/admin/controller/AdminController.java
  server/src/main/java/org/tattour/server/domain/order/controller/OrderController.java
  server/src/main/java/org/tattour/server/domain/order/controller/dto/request/PostOrderReq.java
  server/src/main/java/org/tattour/server/domain/order/domain/Order.java
  server/src/main/java/org/tattour/server/domain/order/provider/OrderProvider.java
  server/src/main/java/org/tattour/server/domain/order/provider/dto/response/GetOrderHistoryListRes.java
  server/src/main/java/org/tattour/server/domain/order/provider/dto/response/GetOrderHistoryRes.java
  server/src/main/java/org/tattour/server/domain/order/provider/dto/response/GetUserOrderHistoryListRes.java
  server/src/main/java/org/tattour/server/domain/order/provider/dto/response/GetUserOrderHistoryRes.java
  server/src/main/java/org/tattour/server/domain/order/provider/dto/response/PageInfoRes.java
  server/src/main/java/org/tattour/server/domain/order/provider/impl/OrderProviderImpl.java
  server/src/main/java/org/tattour/server/domain/order/repository/impl/OrderRepositoryImpl.java
  server/src/main/java/org/tattour/server/domain/order/service/OrderService.java
  server/src/main/java/org/tattour/server/domain/order/service/dto/request/PostOrderReq.java
  server/src/main/java/org/tattour/server/domain/order/service/dto/response/PostOrderRes.java
  server/src/main/java/org/tattour/server/domain/order/service/impl/OrderServiceImpl.java
  server/src/main/java/org/tattour/server/domain/point/domain/PointChargeRequest.java
  server/src/main/java/org/tattour/server/domain/point/domain/UserPointLog.java
  server/src/main/java/org/tattour/server/domain/point/provider/PointProvider.java
  server/src/main/java/org/tattour/server/domain/point/provider/dto/response/GetPointChargeRequestListRes.java
  server/src/main/java/org/tattour/server/domain/point/provider/dto/response/GetPointChargeRequestRes.java
  server/src/main/java/org/tattour/server/domain/point/provider/dto/response/GetUserPointChargeRequestListRes.java
  server/src/main/java/org/tattour/server/domain/point/provider/dto/response/GetUserPointChargeRequestRes.java
  server/src/main/java/org/tattour/server/domain/point/provider/impl/PointProviderImpl.java
  server/src/main/java/org/tattour/server/domain/point/repository/PointChargeRequestRepository.java
  server/src/main/java/org/tattour/server/domain/point/repository/UserPointLogRepository.java
  server/src/main/java/org/tattour/server/domain/point/repository/impl/PointChargeRequestRepositoryImpl.java
  server/src/main/java/org/tattour/server/domain/point/repository/impl/UserPointLogRepositoryImpl.java
  server/src/main/java/org/tattour/server/domain/point/service/PointService.java
  server/src/main/java/org/tattour/server/domain/point/service/dto/request/SavePointChargeRequestReq.java
  server/src/main/java/org/tattour/server/domain/point/service/dto/request/SaveUserPointLogReq.java
  server/src/main/java/org/tattour/server/domain/point/service/impl/PointServiceImpl.java
  server/src/main/java/org/tattour/server/domain/sticker/domain/Sticker.java
  server/src/main/java/org/tattour/server/domain/sticker/provider/dto/response/StickerLikedInfo.java
  server/src/main/java/org/tattour/server/domain/sticker/provider/impl/StickerProviderImpl.java
  server/src/main/java/org/tattour/server/domain/sticker/service/dto/response/StickerInfoRes.java
  server/src/main/java/org/tattour/server/domain/user/controller/UserController.java
  server/src/main/java/org/tattour/server/domain/user/controller/dto/request/PostPointChargeRequest.java
  server/src/main/java/org/tattour/server/domain/user/domain/ProductLiked.java
  server/src/main/java/org/tattour/server/domain/user/domain/User.java
  server/src/main/java/org/tattour/server/domain/user/provider/UserProvider.java
  server/src/main/java/org/tattour/server/domain/user/provider/dto/response/ProductLikedListRes.java
  server/src/main/java/org/tattour/server/domain/user/provider/dto/response/ProductLikedRes.java
  server/src/main/java/org/tattour/server/domain/user/provider/impl/ProductLikedProviderImpl.java
  server/src/main/java/org/tattour/server/domain/user/provider/impl/UserProviderImpl.java
  server/src/main/java/org/tattour/server/domain/user/service/UserService.java
  server/src/main/java/org/tattour/server/domain/user/service/dto/request/UpdateUserPointReq.java
  server/src/main/java/org/tattour/server/domain/user/service/impl/UserServiceImpl.java
  server/src/main/java/org/tattour/server/global/config/resolver/DivisibleBy.java
  server/src/main/java/org/tattour/server/global/dto/SuccessType.java
  server/src/main/java/org/tattour/server/global/exception/ErrorType.java
  server/src/main/java/org/tattour/server/global/util/EntityDtoMapper.java
  server/src/main/java/org/tattour/server/global/util/validator/DivisibleByValidator.java
  server/src/main/java/org/tattour/server/infra/sms/controller/SmsController.java
  server/src/main/resources/logback-spring.xml
Labels: feat, 🐶 찬미

#33 #30 [merge] admin 관련 api 구현 중 merge
  server/build.gradle
  server/src/main/java/org/tattour/server/domain/admin/controller/AdminController.java
  server/src/main/java/org/tattour/server/domain/admin/controller/dto/request/ConfirmPointChargeReq.java
  server/src/main/java/org/tattour/server/domain/point/dao/PointDao.java
  server/src/main/java/org/tattour/server/domain/point/domain/PointChargeRequest.java
  server/src/main/java/org/tattour/server/domain/point/provider/PointProvider.java
  server/src/main/java/org/tattour/server/domain/point/provider/dto/response/GetPointChargeRequestListRes.java
  server/src/main/java/org/tattour/server/domain/point/provider/dto/response/GetPointChargeRequestRes.java
  server/src/main/java/org/tattour/server/domain/point/provider/dto/response/GetUserPointChargeRequestListRes.java
  server/src/main/java/org/tattour/server/domain/point/provider/dto/response/GetUserPointChargeRequestRes.java
  server/src/main/java/org/tattour/server/domain/point/provider/impl/PointProviderImpl.java
  server/src/main/java/org/tattour/server/domain/point/service/PointService.java
  server/src/main/java/org/tattour/server/domain/point/service/dto/request/ConfirmPointChargeRequestReq.java
  server/src/main/java/org/tattour/server/domain/point/service/dto/request/PatchPointChangeRequestReq.java
  server/src/main/java/org/tattour/server/domain/point/service/impl/PointServiceImpl.java
  server/src/main/java/org/tattour/server/global/dto/SuccessType.java
  server/src/main/java/org/tattour/server/global/exception/ErrorType.java
  server/src/main/java/org/tattour/server/global/util/EntityDtoMapper.java
Labels: feat, 🐶 찬미

#36 #30 [feat] admin 관련 api 구현 완료
  server/src/main/java/org/tattour/server/domain/admin/controller/AdminController.java
  server/src/main/java/org/tattour/server/domain/admin/controller/dto/request/CancelPointChargeRequestReq.java
  server/src/main/java/org/tattour/server/domain/admin/controller/dto/request/ConfirmPointChargeRequestReq.java
  server/src/main/java/org/tattour/server/domain/custom/service/CustomService.java
  server/src/main/java/org/tattour/server/domain/custom/service/CustomServiceImpl.java
  server/src/main/java/org/tattour/server/domain/custom/service/dto/request/GetCustomSummaryInfo.java
  server/src/main/java/org/tattour/server/domain/custom/service/dto/response/CustomApplySummaryInfo.java
  server/src/main/java/org/tattour/server/domain/custom/service/dto/response/CustomApplySummaryInfoList.java
  server/src/main/java/org/tattour/server/domain/order/controller/OrderController.java
  server/src/main/java/org/tattour/server/domain/order/controller/dto/request/PatchOrderStatusReq.java
  server/src/main/java/org/tattour/server/domain/order/domain/Order.java
  server/src/main/java/org/tattour/server/domain/order/domain/OrderStatus.java
  server/src/main/java/org/tattour/server/domain/order/provider/OrderProvider.java
  server/src/main/java/org/tattour/server/domain/order/provider/dto/request/GetOrderHistoryAfterDateReq.java
  server/src/main/java/org/tattour/server/domain/order/provider/impl/OrderProviderImpl.java
  server/src/main/java/org/tattour/server/domain/order/repository/impl/OrderRepositoryImpl.java
  server/src/main/java/org/tattour/server/domain/order/service/OrderService.java
  server/src/main/java/org/tattour/server/domain/order/service/dto/request/UpdateOrderStatusReq.java
  server/src/main/java/org/tattour/server/domain/order/service/impl/OrderServiceImpl.java
  server/src/main/java/org/tattour/server/domain/point/dao/PointDao.java
  server/src/main/java/org/tattour/server/domain/point/domain/PointChargeRequest.java
  server/src/main/java/org/tattour/server/domain/point/domain/UserPointLog.java
  server/src/main/java/org/tattour/server/domain/point/provider/PointProvider.java
  server/src/main/java/org/tattour/server/domain/point/provider/dto/request/GetPointChargeRequestAfterDate.java
  server/src/main/java/org/tattour/server/domain/point/provider/dto/request/GetPointLogListReq.java
  server/src/main/java/org/tattour/server/domain/point/provider/dto/response/GetPointLogListRes.java
  server/src/main/java/org/tattour/server/domain/point/provider/dto/response/GetPointLogRes.java
  server/src/main/java/org/tattour/server/domain/point/provider/impl/PointProviderImpl.java
  server/src/main/java/org/tattour/server/domain/point/repository/impl/PointChargeRequestRepositoryImpl.java
  server/src/main/java/org/tattour/server/domain/point/service/PointService.java
  server/src/main/java/org/tattour/server/domain/point/service/dto/request/ConfirmPointChargeRequestDto.java
  server/src/main/java/org/tattour/server/domain/point/service/dto/request/ConfirmPointChargeRequestReq.java
  server/src/main/java/org/tattour/server/domain/point/service/dto/request/PatchPointChangeRequestReq.java
  server/src/main/java/org/tattour/server/domain/point/service/dto/request/SaveUserPointLogReq.java
  server/src/main/java/org/tattour/server/domain/point/service/dto/response/ConfirmPointChargeResponseDto.java
  server/src/main/java/org/tattour/server/domain/point/service/impl/PointServiceImpl.java
  server/src/main/java/org/tattour/server/domain/user/controller/UserController.java
  server/src/main/java/org/tattour/server/domain/user/controller/dto/request/PostPointChargeRequest.java
  server/src/main/java/org/tattour/server/domain/user/domain/User.java
  server/src/main/java/org/tattour/server/domain/user/domain/UserRole.java
  server/src/main/java/org/tattour/server/domain/user/provider/UserProvider.java
  server/src/main/java/org/tattour/server/domain/user/provider/dto/response/GetUserInfoDto.java
  server/src/main/java/org/tattour/server/domain/user/provider/dto/response/GetUserProfileRes.java
  server/src/main/java/org/tattour/server/domain/user/provider/impl/UserProviderImpl.java
  server/src/main/java/org/tattour/server/domain/user/service/impl/UserServiceImpl.java
  server/src/main/java/org/tattour/server/global/config/resolver/UserIdResolver.java
  server/src/main/java/org/tattour/server/global/dto/SuccessType.java
  server/src/main/java/org/tattour/server/global/exception/ErrorType.java
  server/src/main/java/org/tattour/server/global/util/EntityDtoMapper.java
Labels: feat, 🐶 찬미

#37 #26 [FIX] logback 의존성 추가
  server/build.gradle
  server/src/main/java/org/tattour/server/domain/admin/controller/AdminController.java
  server/src/main/java/org/tattour/server/domain/user/controller/UserController.java
  server/src/main/java/org/tattour/server/domain/user/domain/User.java
  server/src/main/java/org/tattour/server/domain/user/provider/impl/ProductLikedProviderImpl.java
  server/src/main/java/org/tattour/server/domain/user/repository/impl/ProductLikedRepositoryImpl.java
  server/src/main/java/org/tattour/server/domain/user/service/UserService.java
  server/src/main/java/org/tattour/server/domain/user/service/impl/UserServiceImpl.java
  server/src/main/java/org/tattour/server/infra/sms/controller/SmsController.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/service/KakaoSocialService.java
Labels: fix, 🐶 찬미

#38 #34 [Feat] 스웨거 세팅, 관리자 api 추가
  server/src/main/java/org/tattour/server/domain/admin/controller/AdminController.java
  server/src/main/java/org/tattour/server/domain/admin/controller/dto/request/CreateStickerReq.java
  server/src/main/java/org/tattour/server/domain/admin/controller/dto/response/CreateStickerRes.java
  server/src/main/java/org/tattour/server/domain/custom/controller/CustomController.java
  server/src/main/java/org/tattour/server/domain/custom/controller/dto/request/UpdateCustomReq.java
  server/src/main/java/org/tattour/server/domain/custom/domain/Custom.java
  server/src/main/java/org/tattour/server/domain/custom/domain/CustomStyle.java
  server/src/main/java/org/tattour/server/domain/custom/domain/CustomTheme.java
  server/src/main/java/org/tattour/server/domain/custom/service/CustomServiceImpl.java
  server/src/main/java/org/tattour/server/domain/order/controller/OrderController.java
  server/src/main/java/org/tattour/server/domain/sticker/controller/StickerController.java
  server/src/main/java/org/tattour/server/domain/sticker/domain/Sticker.java
  server/src/main/java/org/tattour/server/domain/sticker/domain/StickerImage.java
  server/src/main/java/org/tattour/server/domain/sticker/domain/StickerStyle.java
  server/src/main/java/org/tattour/server/domain/sticker/domain/StickerTheme.java
  server/src/main/java/org/tattour/server/domain/sticker/service/StickerService.java
  server/src/main/java/org/tattour/server/domain/sticker/service/StickerServiceImpl.java
  server/src/main/java/org/tattour/server/domain/sticker/service/dto/request/CreateStickerInfo.java
  server/src/main/java/org/tattour/server/domain/style/service/StyleServiceImpl.java
  server/src/main/java/org/tattour/server/domain/user/controller/UserController.java
  server/src/main/java/org/tattour/server/global/config/MultipartJackson2HttpMessageConverter.java
  server/src/main/java/org/tattour/server/global/config/SwaggerConfig.java
  server/src/main/java/org/tattour/server/global/config/resolver/UserIdResolver.java
  server/src/main/java/org/tattour/server/global/exception/ErrorType.java
  server/src/main/java/org/tattour/server/global/util/AuditingTimeEntity.java
  server/src/main/resources/logback-spring.xml
Labels: feat, 🐱서린

#40 #26 [FIX] logback-spring.xml
  server/src/main/resources/logback-spring.xml
Labels: fix, 🐶 찬미

#42 #41 [FIX] dto validation
  server/.gitignore
  server/src/main/java/org/tattour/server/domain/admin/controller/AdminController.java
  server/src/main/java/org/tattour/server/domain/admin/controller/dto/request/CancelPointChargeRequestReq.java
  server/src/main/java/org/tattour/server/domain/admin/controller/dto/request/ConfirmPointChargeRequestReq.java
  server/src/main/java/org/tattour/server/domain/admin/controller/dto/request/CreateStickerReq.java
  server/src/main/java/org/tattour/server/domain/order/controller/OrderController.java
  server/src/main/java/org/tattour/server/domain/order/controller/dto/request/GetOrderSheetReq.java
  server/src/main/java/org/tattour/server/domain/order/controller/dto/request/PatchOrderStatusReq.java
  server/src/main/java/org/tattour/server/domain/order/controller/dto/request/PostOrderReq.java
  server/src/main/java/org/tattour/server/domain/user/controller/UserController.java
  server/src/main/java/org/tattour/server/domain/user/controller/dto/request/DeleteProductLikedReq.java
  server/src/main/java/org/tattour/server/domain/user/controller/dto/request/GetVerifyCodeReq.java
  server/src/main/java/org/tattour/server/domain/user/controller/dto/request/LoginReq.java
  server/src/main/java/org/tattour/server/domain/user/controller/dto/request/PatchUserInfoReq.java
  server/src/main/java/org/tattour/server/domain/user/controller/dto/request/PostPointChargeRequest.java
  server/src/main/java/org/tattour/server/domain/user/controller/dto/request/PostProductLikedReq.java
  server/src/main/java/org/tattour/server/domain/user/controller/dto/request/PostUserShippingAddrReq.java
  server/src/main/java/org/tattour/server/infra/sms/controller/SmsController.java
  server/src/main/java/org/tattour/server/infra/sms/controller/dto/request/PostSendCodeReq.java
Labels: FIX, 🐶 찬미

#46 #43 [FIX] 전화번호 정보 yml 파일로 이전
  server/src/main/java/org/tattour/server/infra/sms/service/impl/SmsServiceImpl.java
Labels: FIX, 🐶 찬미

#45 #34 [FEAT] 스티커 관리자 api, 디스코드 알림봇 구현
  server/build.gradle
  server/src/main/java/org/tattour/server/domain/admin/controller/AdminController.java
  server/src/main/java/org/tattour/server/domain/custom/controller/CustomController.java
  server/src/main/java/org/tattour/server/domain/custom/service/CustomServiceImpl.java
  server/src/main/java/org/tattour/server/domain/custom/service/dto/request/UpdateCustomInfo.java
  server/src/main/java/org/tattour/server/domain/custom/service/dto/response/CustomInfo.java
  server/src/main/java/org/tattour/server/domain/order/controller/OrderController.java
  server/src/main/java/org/tattour/server/domain/order/service/OrderService.java
  server/src/main/java/org/tattour/server/domain/order/service/impl/OrderServiceImpl.java
  server/src/main/java/org/tattour/server/domain/point/service/impl/PointServiceImpl.java
  server/src/main/java/org/tattour/server/domain/sticker/controller/StickerController.java
  server/src/main/java/org/tattour/server/domain/sticker/service/dto/response/StickerInfo.java
  server/src/main/java/org/tattour/server/domain/sticker/service/dto/response/StickerSummary.java
  server/src/main/java/org/tattour/server/domain/user/controller/UserController.java
  server/src/main/java/org/tattour/server/global/config/resolver/UserIdResolver.java
  server/src/main/java/org/tattour/server/infra/discord/client/DiscordApiClient.java
  server/src/main/java/org/tattour/server/infra/discord/dto/resquest/CustomApplyDiscordMessage.java
  server/src/main/java/org/tattour/server/infra/discord/dto/resquest/DiscordCustomImage.java
  server/src/main/java/org/tattour/server/infra/discord/dto/resquest/DiscordMessageReq.java
  server/src/main/java/org/tattour/server/infra/discord/dto/resquest/OrderStickerDiscordMessage.java
  server/src/main/java/org/tattour/server/infra/discord/dto/resquest/PointChargeDiscordMessage.java
  server/src/main/java/org/tattour/server/infra/discord/property/CustomWebhookProperty.java
  server/src/main/java/org/tattour/server/infra/discord/property/OrderWebhookProperty.java
  server/src/main/java/org/tattour/server/infra/discord/property/PointWebhookProperty.java
  server/src/main/java/org/tattour/server/infra/discord/service/DiscordMessageService.java
Labels: FEAT, 🐱서린

#49 #35 [DOCS] api docs
  server/src/main/java/org/tattour/server/ServerApplication.java
  server/src/main/java/org/tattour/server/domain/admin/controller/AdminController.java
  server/src/main/java/org/tattour/server/domain/order/controller/OrderController.java
  server/src/main/java/org/tattour/server/domain/user/controller/UserController.java
  server/src/main/java/org/tattour/server/domain/user/controller/dto/request/DeleteProductLikedReq.java
  server/src/main/java/org/tattour/server/domain/user/controller/dto/request/GetVerifyCodeReq.java
  server/src/main/java/org/tattour/server/domain/user/controller/dto/request/LoginReq.java
  server/src/main/java/org/tattour/server/domain/user/controller/dto/request/PatchUserInfoReq.java
  server/src/main/java/org/tattour/server/domain/user/controller/dto/request/PostPointChargeRequest.java
  server/src/main/java/org/tattour/server/domain/user/controller/dto/request/PostProductLikedReq.java
  server/src/main/java/org/tattour/server/domain/user/controller/dto/request/PostUserShippingAddrReq.java
  server/src/main/java/org/tattour/server/domain/user/controller/dto/response/GetVerifyCodeRes.java
  server/src/main/java/org/tattour/server/domain/user/controller/dto/response/LoginRes.java
  server/src/main/java/org/tattour/server/domain/user/provider/dto/response/GetUserProfileRes.java
  server/src/main/java/org/tattour/server/domain/user/provider/dto/response/ProductLikedListRes.java
  server/src/main/java/org/tattour/server/global/config/WebConfig.java
  server/src/main/java/org/tattour/server/global/config/resolver/UserIdResolver.java
  server/src/main/java/org/tattour/server/global/dto/FailResponse.java
  server/src/main/java/org/tattour/server/global/dto/SuccessResponse.java
  server/src/main/java/org/tattour/server/global/exception/ErrorType.java
  server/src/main/java/org/tattour/server/infra/sms/provider/impl/PhoneNumberVerificationCodeProviderImpl.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/service/SocialService.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/service/SocialServiceProvider.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/service/dto/request/SocialLoginRequest.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/service/dto/response/SocialLoginResponse.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/service/impl/KakaoSocialService.java
Labels: DOCS, 🐶 찬미

#51 #35 [DOCS] api docs 설명 추가
  server/src/main/java/org/tattour/server/domain/admin/controller/AdminController.java
  server/src/main/java/org/tattour/server/domain/order/controller/OrderController.java
  server/src/main/java/org/tattour/server/domain/order/controller/dto/request/GetOrderSheetReq.java
  server/src/main/java/org/tattour/server/domain/order/controller/dto/request/PostOrderReq.java
  server/src/main/java/org/tattour/server/domain/order/controller/dto/response/GetOrderSheetRes.java
  server/src/main/java/org/tattour/server/domain/order/provider/dto/response/GetOrderAmountRes.java
  server/src/main/java/org/tattour/server/domain/order/provider/dto/response/GetUserOrderHistoryListRes.java
  server/src/main/java/org/tattour/server/domain/order/provider/dto/response/GetUserOrderHistoryRes.java
  server/src/main/java/org/tattour/server/domain/order/provider/dto/response/GetUserOrderPointRes.java
  server/src/main/java/org/tattour/server/domain/order/provider/impl/OrderProviderImpl.java
  server/src/main/java/org/tattour/server/domain/sticker/provider/dto/response/GetOrderSheetStickerInfo.java
  server/src/main/java/org/tattour/server/domain/sticker/provider/dto/response/StickerLikedInfo.java
  server/src/main/java/org/tattour/server/domain/user/controller/UserController.java
  server/src/main/java/org/tattour/server/domain/user/controller/dto/request/LoginReq.java
  server/src/main/java/org/tattour/server/domain/user/controller/dto/request/PatchUserInfoReq.java
  server/src/main/java/org/tattour/server/domain/user/controller/dto/request/PostPointChargeRequest.java
  server/src/main/java/org/tattour/server/domain/user/controller/dto/request/PostUserShippingAddrReq.java
  server/src/main/java/org/tattour/server/domain/user/provider/dto/response/GetUserProfileRes.java
  server/src/main/java/org/tattour/server/infra/sms/controller/SmsController.java
Labels: DOCS, 🐶 찬미

#54 #50 [FIX] 서버 배포 후 버그 해결
  server/src/main/java/org/tattour/server/ServerApplication.java
  server/src/main/java/org/tattour/server/domain/admin/controller/AdminController.java
  server/src/main/java/org/tattour/server/domain/order/controller/OrderController.java
  server/src/main/java/org/tattour/server/domain/point/provider/dto/response/GetPointChargeRequestListRes.java
  server/src/main/java/org/tattour/server/domain/point/provider/dto/response/GetPointChargeRequestRes.java
  server/src/main/java/org/tattour/server/domain/point/service/impl/PointServiceImpl.java
  server/src/main/java/org/tattour/server/domain/user/domain/User.java
  server/src/main/java/org/tattour/server/domain/user/provider/UserProvider.java
  server/src/main/java/org/tattour/server/domain/user/provider/impl/UserProviderImpl.java
  server/src/main/java/org/tattour/server/domain/user/repository/impl/UserRepositoryImpl.java
  server/src/main/java/org/tattour/server/domain/user/service/dto/request/SaveUserReq.java
  server/src/main/java/org/tattour/server/global/config/WebConfig.java
  server/src/main/java/org/tattour/server/infra/discord/dto/resquest/CustomApplyDiscordMessage.java
  server/src/main/java/org/tattour/server/infra/discord/dto/resquest/PointChargeDiscordMessage.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/dto/response/KakaoUserRes.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/service/impl/KakaoSocialService.java
  server/src/main/resources/logback-spring.xml
Labels: FIX, 🐶 찬미

#55 #50 [FIX] Update ServerApplication.java
  server/src/main/java/org/tattour/server/ServerApplication.java
Labels: FIX, 🐶 찬미

#59 #56 [FEAT, FIX] Discount 관련 api 추가, 버그 수정
  server/src/main/java/org/tattour/server/domain/admin/controller/AdminController.java
  server/src/main/java/org/tattour/server/domain/admin/controller/dto/request/ApplyStickerDiscountReq.java
  server/src/main/java/org/tattour/server/domain/admin/controller/dto/request/CreateDiscountReq.java
  server/src/main/java/org/tattour/server/domain/admin/controller/dto/request/UpdateCustomProcessReq.java
  server/src/main/java/org/tattour/server/domain/custom/controller/CustomController.java
  server/src/main/java/org/tattour/server/domain/discount/domain/Discount.java
  server/src/main/java/org/tattour/server/domain/discount/exception/NotFoundDiscountException.java
  server/src/main/java/org/tattour/server/domain/discount/repository/DiscountRepository.java
  server/src/main/java/org/tattour/server/domain/discount/repository/impl/DiscountRepositoryImpl.java
  server/src/main/java/org/tattour/server/domain/discount/service/DiscountService.java
  server/src/main/java/org/tattour/server/domain/discount/service/DiscountServiceImpl.java
  server/src/main/java/org/tattour/server/domain/discount/service/dto/request/DiscountInfo.java
  server/src/main/java/org/tattour/server/domain/sticker/domain/Sticker.java
  server/src/main/java/org/tattour/server/domain/sticker/exception/NotFoundStickerException.java
  server/src/main/java/org/tattour/server/domain/sticker/service/StickerServiceImpl.java
  server/src/main/java/org/tattour/server/domain/sticker/service/dto/response/StickerInfo.java
  server/src/main/java/org/tattour/server/global/dto/SuccessType.java
Labels: FEAT, FIX, 🐱서린

#60 #35 [DOCS] Swagger API 명세서 설명 추가
  server/src/main/java/org/tattour/server/ServerApplication.java
  server/src/main/java/org/tattour/server/domain/admin/controller/AdminController.java
  server/src/main/java/org/tattour/server/domain/admin/controller/dto/request/CancelPointChargeRequestReq.java
  server/src/main/java/org/tattour/server/domain/admin/controller/dto/request/ConfirmPointChargeRequestReq.java
  server/src/main/java/org/tattour/server/domain/custom/controller/CustomController.java
  server/src/main/java/org/tattour/server/domain/custom/service/dto/response/CustomApplySummaryInfo.java
  server/src/main/java/org/tattour/server/domain/custom/service/dto/response/CustomApplySummaryInfoList.java
  server/src/main/java/org/tattour/server/domain/order/controller/OrderController.java
  server/src/main/java/org/tattour/server/domain/order/controller/dto/request/PatchOrderStatusReq.java
  server/src/main/java/org/tattour/server/domain/order/service/dto/request/UpdateOrderStatusReq.java
  server/src/main/java/org/tattour/server/domain/order/service/impl/OrderServiceImpl.java
  server/src/main/java/org/tattour/server/domain/point/service/dto/response/ConfirmPointChargeResponseDto.java
  server/src/main/java/org/tattour/server/domain/point/service/impl/PointServiceImpl.java
  server/src/main/java/org/tattour/server/domain/user/controller/UserController.java
  server/src/main/java/org/tattour/server/domain/user/controller/dto/request/GetVerifyCodeReq.java
  server/src/main/java/org/tattour/server/domain/user/provider/dto/response/GetUserInfoDto.java
  server/src/main/java/org/tattour/server/global/dto/SuccessType.java
  server/src/main/java/org/tattour/server/infra/sms/controller/SmsController.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/service/impl/KakaoSocialService.java
Labels: DOCS, FIX, 🐶 찬미

#61 #35 [FIX] jwt 설정 다시 삭제
  server/build.gradle
  server/src/main/java/org/tattour/server/domain/admin/controller/AdminController.java
  server/src/main/java/org/tattour/server/domain/custom/controller/CustomController.java
  server/src/main/java/org/tattour/server/domain/order/controller/OrderController.java
  server/src/main/java/org/tattour/server/domain/user/controller/UserController.java
  server/src/main/java/org/tattour/server/infra/sms/controller/SmsController.java
Labels: DOCS, FIX, 🐶 찬미

#62 #50 [FIX] 전화번호 인증 post 메소드에 request body로 요청하도록 수정
  server/src/main/java/org/tattour/server/domain/user/controller/UserController.java
  server/src/main/java/org/tattour/server/domain/user/controller/dto/request/PostVerifyCodeReq.java
Labels: FIX, 🐶 찬미

#65 #50 [FIX] 인증번호 검증 api POST -> GET
  server/src/main/java/org/tattour/server/domain/user/controller/UserController.java
Labels: FIX, 🐶 찬미

#66 #50 [FIX] 좋아요한 타투 스티커 삭제, 결제페이지 불러오기 api 수정
  server/src/main/java/org/tattour/server/domain/order/controller/OrderController.java
  server/src/main/java/org/tattour/server/domain/order/controller/dto/request/GetOrderSheetReq.java
  server/src/main/java/org/tattour/server/domain/order/provider/OrderProvider.java
  server/src/main/java/org/tattour/server/domain/order/provider/impl/OrderProviderImpl.java
  server/src/main/java/org/tattour/server/domain/user/controller/UserController.java
  server/src/main/java/org/tattour/server/domain/user/controller/dto/request/DeleteProductLikedReq.java
  server/src/main/java/org/tattour/server/domain/user/provider/ProductLikedProvider.java
  server/src/main/java/org/tattour/server/domain/user/provider/impl/ProductLikedProviderImpl.java
  server/src/main/java/org/tattour/server/domain/user/repository/impl/ProductLikedRepositoryImpl.java
  server/src/main/java/org/tattour/server/domain/user/service/ProductLikedService.java
  server/src/main/java/org/tattour/server/domain/user/service/impl/ProductLikedServiceImpl.java
Labels: FIX, 🐶 찬미

#68 #50 [FIX] 결제 시트 가져오기 할인 적용 여부로 수정하기
  server/src/main/java/org/tattour/server/domain/order/controller/OrderController.java
  server/src/main/java/org/tattour/server/domain/order/provider/impl/OrderProviderImpl.java
Labels: FIX, 🐶 찬미

#69 #50 [FIX] 결제 페이지 불러오기 총 결제금액 오류 수정
  server/src/main/java/org/tattour/server/domain/order/provider/impl/OrderProviderImpl.java
Labels: FIX, 🐶 찬미

#72 #50 [FIX] Update deploy.sh
  scripts/deploy.sh
Labels: FIX, 🐱서린

#73 #50 [FIX] 좋아요 누른 타투 스티커 내역 가져오기 response에 productLikedId 추가
  .gitignore
  server/build.gradle
  server/src/main/java/org/tattour/server/domain/admin/controller/AdminController.java
  server/src/main/java/org/tattour/server/domain/discount/domain/Discount.java
  server/src/main/java/org/tattour/server/domain/sticker/domain/Sticker.java
  server/src/main/java/org/tattour/server/domain/sticker/provider/dto/response/StickerLikedInfo.java
  server/src/main/java/org/tattour/server/domain/user/controller/UserController.java
  server/src/main/java/org/tattour/server/domain/user/provider/UserProvider.java
  server/src/main/java/org/tattour/server/domain/user/provider/impl/ProductLikedProviderImpl.java
  server/src/main/java/org/tattour/server/domain/user/provider/impl/UserProviderImpl.java
  server/src/main/java/org/tattour/server/global/util/EntityDtoMapper.java
  server/src/main/resources/templates/css/style.css
  server/src/main/resources/templates/index.mustache
  server/src/main/resources/templates/layout/user.mustache
Labels: FIX, 🐶 찬미

#74 #50 [FIX] Update logback-spring.xml
  server/src/main/resources/logback-spring.xml
Labels: FIX, 🐶 찬미

#77 #50 [FIX] 좋아요 누른 타투 삭제 userId, stickerId로 삭제
  server/src/main/java/org/tattour/server/domain/user/controller/UserController.java
  server/src/main/java/org/tattour/server/domain/user/provider/ProductLikedProvider.java
  server/src/main/java/org/tattour/server/domain/user/provider/impl/ProductLikedProviderImpl.java
  server/src/main/java/org/tattour/server/domain/user/service/ProductLikedService.java
  server/src/main/java/org/tattour/server/domain/user/service/impl/ProductLikedServiceImpl.java
Labels: FIX, 🐶 찬미

#80 #57 [FIX] admin 페이지 파일 이름 변경
  server/src/main/resources/templates/main.mustache
Labels: FIX, 🐶 찬미

#94 #50 [FIX] serivce 순환참조 에러로 CustomProvider 추가 후 메소드 이전
  server/src/main/java/org/tattour/server/ServerApplication.java
  server/src/main/java/org/tattour/server/domain/admin/controller/AdminController.java
  server/src/main/java/org/tattour/server/domain/custom/provider/CustomProvider.java
  server/src/main/java/org/tattour/server/domain/custom/service/CustomService.java
  server/src/main/java/org/tattour/server/domain/custom/service/CustomServiceImpl.java
  server/src/main/java/org/tattour/server/domain/order/controller/OrderController.java
  server/src/main/java/org/tattour/server/domain/order/repository/impl/OrderRepositoryImpl.java
  server/src/main/java/org/tattour/server/domain/point/service/impl/CustomProviderImpl.java
  server/src/main/java/org/tattour/server/domain/point/service/impl/PointServiceImpl.java
  server/src/main/java/org/tattour/server/domain/user/controller/UserController.java
  server/src/main/java/org/tattour/server/domain/user/provider/impl/ProductLikedProviderImpl.java
  server/src/main/java/org/tattour/server/domain/user/repository/impl/ProductLikedRepositoryImpl.java
  server/src/main/java/org/tattour/server/domain/user/service/UserService.java
  server/src/main/resources/logback-spring.xml
Labels: FIX, 🐶 찬미

#95 #50 [FIX] getter 어노테이션 boolean 변수 get메소드 네이밍 에러 해결
  server/build.gradle
  server/src/main/java/org/tattour/server/domain/admin/controller/AdminController.java
  server/src/main/java/org/tattour/server/domain/order/provider/dto/response/GetOrderHistoryRes.java
  server/src/main/java/org/tattour/server/domain/order/provider/dto/response/GetUserOrderHistoryRes.java
  server/src/main/java/org/tattour/server/domain/order/provider/dto/response/GetUserOrderPointRes.java
  server/src/main/java/org/tattour/server/domain/order/provider/impl/OrderProviderImpl.java
  server/src/main/java/org/tattour/server/domain/point/domain/PointChargeRequest.java
  server/src/main/java/org/tattour/server/domain/point/provider/dto/response/GetPointChargeRequestRes.java
  server/src/main/java/org/tattour/server/domain/point/provider/dto/response/GetPointLogRes.java
  server/src/main/java/org/tattour/server/domain/user/controller/UserController.java
  server/src/main/java/org/tattour/server/domain/user/controller/dto/response/GetVerifyCodeRes.java
  server/src/main/java/org/tattour/server/domain/user/controller/dto/response/LoginRes.java
  server/src/main/java/org/tattour/server/domain/user/provider/ProductLikedProvider.java
  server/src/main/java/org/tattour/server/domain/user/provider/UserProvider.java
  server/src/main/java/org/tattour/server/domain/user/provider/impl/ProductLikedProviderImpl.java
  server/src/main/java/org/tattour/server/domain/user/provider/impl/UserProviderImpl.java
  server/src/main/java/org/tattour/server/global/config/jwt/JwtService.java
  server/src/main/java/org/tattour/server/infra/discord/service/DiscordMessageService.java
  server/src/main/java/org/tattour/server/infra/sms/provider/PhoneNumberVerificationCodeProvider.java
  server/src/main/java/org/tattour/server/infra/sms/provider/impl/PhoneNumberVerificationCodeProviderImpl.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/service/dto/response/SocialLoginResponse.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/service/impl/KakaoSocialService.java
  server/src/main/resources/templates/index.mustache
Labels: FIX, 🐶 찬미

#96 #50 [FIX] redirect url 변경
  .gitignore
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/service/impl/KakaoSocialService.java
Labels: FIX, 🐶 찬미

#100 #50 [FIX] 소셜 로그인 리다이렉트 url 변경
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/service/impl/KakaoSocialService.java
Labels: FIX, 🐶 찬미
