Repository TEAM-TATTOUR/tattour-server, pull requests merged in 2023-08, with the labels that each got.

#103 #56 [FIX] login login call back 주소 변경
  server/src/main/java/org/tattour/server/domain/user/controller/UserController.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/service/dto/request/SocialLoginRequest.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/service/impl/KakaoSocialService.java
Labels: FIX, 🐱서린

#106 #105 [CHORE] test
  README.md
Labels: CHORE

#112 #57 [REFACTOR] Facade 패턴 적용 완료, order sheet 가져오기 api 수정
  server/src/main/generated/org/tattour/server/global/util/EntityDtoMapperImpl.java
  server/src/main/java/org/tattour/server/domain/admin/controller/AdminController.java
  server/src/main/java/org/tattour/server/domain/custom/facade/dto/request/ReadCustomSummaryReq.java
  server/src/main/java/org/tattour/server/domain/custom/facade/dto/response/ReadCustomSummaryRes.java
  server/src/main/java/org/tattour/server/domain/custom/facade/impl/CustomFacadeImpl.java
  server/src/main/java/org/tattour/server/domain/custom/provider/CustomProvider.java
  server/src/main/java/org/tattour/server/domain/custom/provider/impl/CustomProviderImpl.java
  server/src/main/java/org/tattour/server/domain/custom/repository/CustomRepository.java
  server/src/main/java/org/tattour/server/domain/order/controller/dto/response/ReadOrderSheetRes.java
  server/src/main/java/org/tattour/server/domain/order/facade/OrderFacade.java
  server/src/main/java/org/tattour/server/domain/order/facade/dto/request/UpdateOrderStatusReq.java
  server/src/main/java/org/tattour/server/domain/order/facade/dto/response/ReadOrderHistoryListRes.java
  server/src/main/java/org/tattour/server/domain/order/facade/impl/OrderFacadeImpl.java
  server/src/main/java/org/tattour/server/domain/order/provider/OrderProvider.java
  server/src/main/java/org/tattour/server/domain/order/provider/impl/OrderProviderImpl.java
  server/src/main/java/org/tattour/server/domain/order/provider/vo/OrderHistoryInfo.java
  server/src/main/java/org/tattour/server/domain/order/service/OrderService.java
  server/src/main/java/org/tattour/server/domain/order/service/impl/OrderServiceImpl.java
  server/src/main/java/org/tattour/server/domain/point/dao/PointDao.java
  server/src/main/java/org/tattour/server/domain/point/domain/PointLogCategory.java
  server/src/main/java/org/tattour/server/domain/point/domain/UserPointLog.java
  server/src/main/java/org/tattour/server/domain/point/facade/PointFacade.java
  server/src/main/java/org/tattour/server/domain/point/facade/dto/request/ConfirmPointChargeReq.java
  server/src/main/java/org/tattour/server/domain/point/facade/dto/request/ReadPointChargeRequestListReq.java
  server/src/main/java/org/tattour/server/domain/point/facade/dto/request/ReadPointLogListReq.java
  server/src/main/java/org/tattour/server/domain/point/facade/dto/response/ConfirmPointChargeRes.java
  server/src/main/java/org/tattour/server/domain/point/facade/impl/PointFacadeImpl.java
  server/src/main/java/org/tattour/server/domain/point/provider/PointProvider.java
  server/src/main/java/org/tattour/server/domain/point/provider/impl/PointProviderImpl.java
  server/src/main/java/org/tattour/server/domain/point/service/PointService.java
  server/src/main/java/org/tattour/server/domain/point/service/dto/request/ConfirmPointChargeRequestDto.java
  server/src/main/java/org/tattour/server/domain/point/service/dto/request/PatchPointChangeRequestReq.java
  server/src/main/java/org/tattour/server/domain/point/service/dto/request/SaveUserPointLogReq.java
  server/src/main/java/org/tattour/server/domain/point/service/dto/response/ConfirmPointChargeResponseDto.java
  server/src/main/java/org/tattour/server/domain/point/service/impl/PointServiceImpl.java
  server/src/main/java/org/tattour/server/domain/sticker/provider/StickerProvider.java
  server/src/main/java/org/tattour/server/domain/sticker/provider/impl/StickerProviderImpl.java
  server/src/main/java/org/tattour/server/domain/user/controller/UserController.java
  server/src/main/java/org/tattour/server/domain/user/facade/dto/response/ReadUserProfileRes.java
  server/src/main/java/org/tattour/server/domain/user/facade/impl/UserFacadeImpl.java
  server/src/main/java/org/tattour/server/domain/user/provider/UserProvider.java
  server/src/main/java/org/tattour/server/domain/user/provider/impl/UserProviderImpl.java
  server/src/main/java/org/tattour/server/domain/user/provider/vo/HomeUserInfo.java
  server/src/main/java/org/tattour/server/domain/user/provider/vo/UserContactInfo.java
  server/src/main/java/org/tattour/server/domain/user/provider/vo/UserProfileInfo.java
  server/src/main/java/org/tattour/server/domain/user/service/UserService.java
  server/src/main/java/org/tattour/server/domain/user/service/impl/UserServiceImpl.java
  server/src/main/java/org/tattour/server/global/exception/ControllerExceptionHandler.java
  server/src/main/java/org/tattour/server/global/util/EntityDtoMapper.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/service/dto/request/response/KakaoAccessTokenRes.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/service/dto/request/response/KakaoUserInfoRes.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/service/dto/request/response/SocialAccessTokenRes.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/service/dto/request/response/SocialUserInfoRes.java
Labels: REFACTOR

#114 #56 [FIX, REFACTOR] 리펙토링 최종
  server/src/main/generated/org/tattour/server/global/util/EntityDtoMapperImpl.java
  server/src/main/java/org/tattour/server/domain/admin/controller/AdminController.java
  server/src/main/java/org/tattour/server/domain/admin/controller/dto/request/CancelPointChargeRequestReq.java
  server/src/main/java/org/tattour/server/domain/admin/controller/dto/request/PatchCustomProcessReq.java
  server/src/main/java/org/tattour/server/domain/admin/controller/dto/request/PostDiscountReq.java
  server/src/main/java/org/tattour/server/domain/admin/controller/dto/request/PostStickerReq.java
  server/src/main/java/org/tattour/server/domain/admin/controller/dto/response/PostStickerRes.java
  server/src/main/java/org/tattour/server/domain/custom/controller/CustomController.java
  server/src/main/java/org/tattour/server/domain/custom/controller/dto/request/PatchCustomReq.java
  server/src/main/java/org/tattour/server/domain/custom/controller/dto/request/PostCustomReq.java
  server/src/main/java/org/tattour/server/domain/custom/controller/dto/response/PatchCustomRes.java
  server/src/main/java/org/tattour/server/domain/custom/domain/Custom.java
  server/src/main/java/org/tattour/server/domain/custom/domain/CustomStyle.java
  server/src/main/java/org/tattour/server/domain/custom/domain/CustomTheme.java
  server/src/main/java/org/tattour/server/domain/custom/exception/InvalidCustomCompletedException.java
  server/src/main/java/org/tattour/server/domain/custom/exception/InvalidCustomPriceException.java
  server/src/main/java/org/tattour/server/domain/custom/facade/CustomFacade.java
  server/src/main/java/org/tattour/server/domain/custom/facade/dto/request/UpdateCustomReq.java
  server/src/main/java/org/tattour/server/domain/custom/facade/dto/response/ReadCustomRes.java
  server/src/main/java/org/tattour/server/domain/custom/facade/impl/CustomFacadeImpl.java
  server/src/main/java/org/tattour/server/domain/custom/provider/CustomProvider.java
  server/src/main/java/org/tattour/server/domain/custom/provider/impl/CustomProviderImpl.java
  server/src/main/java/org/tattour/server/domain/custom/repository/CustomImageRepository.java
  server/src/main/java/org/tattour/server/domain/custom/repository/CustomRepository.java
  server/src/main/java/org/tattour/server/domain/custom/repository/CustomStyleRepository.java
  server/src/main/java/org/tattour/server/domain/custom/repository/CustomThemeRepository.java
  server/src/main/java/org/tattour/server/domain/custom/service/CustomImageService.java
  server/src/main/java/org/tattour/server/domain/custom/service/CustomService.java
  server/src/main/java/org/tattour/server/domain/custom/service/CustomStyleService.java
  server/src/main/java/org/tattour/server/domain/custom/service/CustomThemeService.java
  server/src/main/java/org/tattour/server/domain/custom/service/impl/CustomImageServiceImpl.java
  server/src/main/java/org/tattour/server/domain/custom/service/impl/CustomServiceImpl.java
  server/src/main/java/org/tattour/server/domain/custom/service/impl/CustomStyleServiceImpl.java
  server/src/main/java/org/tattour/server/domain/custom/service/impl/CustomThemeServiceImpl.java
  server/src/main/java/org/tattour/server/domain/discount/facade/DiscountFacade.java
  server/src/main/java/org/tattour/server/domain/discount/facade/dto/request/CreateDiscountReq.java
  server/src/main/java/org/tattour/server/domain/discount/facade/impl/DiscountFacadeImpl.java
  server/src/main/java/org/tattour/server/domain/point/facade/impl/PointFacadeImpl.java
  server/src/main/java/org/tattour/server/domain/search/controller/SearchController.java
  server/src/main/java/org/tattour/server/domain/sticker/controller/StickerController.java
  server/src/main/java/org/tattour/server/domain/sticker/facade/StickerFacade.java
  server/src/main/java/org/tattour/server/domain/sticker/facade/dto/response/ReadOrderSheetStickerRes.java
  server/src/main/java/org/tattour/server/domain/sticker/facade/impl/StickerFacadeImpl.java
  server/src/main/java/org/tattour/server/domain/sticker/service/StickerImageService.java
  server/src/main/java/org/tattour/server/domain/sticker/service/StickerServiceImpl.java
  server/src/main/java/org/tattour/server/domain/style/controller/StyleController.java
  server/src/main/java/org/tattour/server/domain/style/controller/dto/response/GetStyleListRes.java
  server/src/main/java/org/tattour/server/domain/style/controller/dto/response/GetStyleSummaryListRes.java
  server/src/main/java/org/tattour/server/domain/style/domain/Style.java
  server/src/main/java/org/tattour/server/domain/theme/controller/ThemeController.java
  server/src/main/java/org/tattour/server/domain/theme/domain/Theme.java
  server/src/main/java/org/tattour/server/domain/user/controller/UserController.java
  server/src/main/java/org/tattour/server/domain/user/domain/User.java
  server/src/main/java/org/tattour/server/domain/user/facade/dto/request/CreateLoginReq.java
  server/src/main/java/org/tattour/server/domain/user/facade/impl/UserFacadeImpl.java
  server/src/main/java/org/tattour/server/domain/user/service/impl/UserServiceImpl.java
  server/src/main/java/org/tattour/server/infra/sms/controller/SmsController.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/service/dto/request/GetSocialLoginReq.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/service/impl/KakaoSocialService.java
Labels: FIX, REFACTOR, 🐱서린

#115 #57 [CHORE] 변수명, 폴더 구조 수정
  server/src/main/java/org/tattour/server/domain/user/controller/dto/response/PostLoginRes.java
  server/src/main/java/org/tattour/server/domain/user/facade/impl/UserFacadeImpl.java
  server/src/main/java/org/tattour/server/global/exception/ErrorType.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/KakaoApiClient.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/KakaoAuthApiClient.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/service/dto/response/KakaoAccessTokenRes.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/service/dto/response/KakaoAccount.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/service/dto/response/KakaoUserInfoRes.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/service/dto/response/SocialAccessTokenRes.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/service/dto/response/SocialUserInfoRes.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/service/impl/KakaoSocialService.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/service/vo/KakaoLoginInfo.java
  server/src/main/java/org/tattour/server/infra/socialLogin/client/kakao/service/vo/SocialLoginInfo.java
Labels: FIX

#116 #57 [FIX] dev 서버 CORS allowdOrigins all로 변경
  server/src/main/java/org/tattour/server/global/config/WebConfig.java
Labels: FIX

#117 #57 [FIX, REFACTOR] CORS 관련 설정 수정
  server/src/main/java/org/tattour/server/global/config/WebConfig.java
Labels: FIX, REFACTOR

#118 #56 [FIX] 커스텀 도안 신청 에러 수정
  server/src/main/generated/org/tattour/server/global/util/EntityDtoMapperImpl.java
  server/src/main/java/org/tattour/server/domain/custom/facade/impl/CustomFacadeImpl.java
  server/src/main/java/org/tattour/server/domain/custom/repository/CustomStyleRepository.java
  server/src/main/java/org/tattour/server/domain/custom/service/CustomService.java
  server/src/main/java/org/tattour/server/domain/custom/service/CustomThemeService.java
  server/src/main/java/org/tattour/server/domain/custom/service/impl/CustomServiceImpl.java
  server/src/main/java/org/tattour/server/domain/custom/service/impl/CustomStyleServiceImpl.java
  server/src/main/java/org/tattour/server/global/config/WebConfig.java
Labels: FIX, 🐱서린

#120 #119 [REFACTOR] Custom, Sticker 성능 최적화
  server/src/main/java/org/tattour/server/domain/custom/domain/Custom.java
  server/src/main/java/org/tattour/server/domain/custom/facade/CustomFacade.java
  server/src/main/java/org/tattour/server/domain/custom/facade/dto/response/ReadCustomRes.java
  server/src/main/java/org/tattour/server/domain/custom/facade/impl/CustomFacadeImpl.java
  server/src/main/java/org/tattour/server/domain/custom/provider/CustomProvider.java
  server/src/main/java/org/tattour/server/domain/custom/provider/impl/CustomProviderImpl.java
  server/src/main/java/org/tattour/server/domain/custom/repository/CustomRepository.java
  server/src/main/java/org/tattour/server/domain/discount/domain/Discount.java
  server/src/main/java/org/tattour/server/domain/point/facade/impl/PointFacadeImpl.java
  server/src/main/java/org/tattour/server/domain/search/facade/impl/SearchFacadeImpl.java
  server/src/main/java/org/tattour/server/domain/sticker/controller/StickerController.java
  server/src/main/java/org/tattour/server/domain/sticker/domain/Sticker.java
  server/src/main/java/org/tattour/server/domain/sticker/facade/StickerFacade.java
  server/src/main/java/org/tattour/server/domain/sticker/facade/impl/StickerFacadeImpl.java
  server/src/main/java/org/tattour/server/domain/sticker/provider/StickerProvider.java
  server/src/main/java/org/tattour/server/domain/sticker/provider/impl/StickerProviderImpl.java
  server/src/main/java/org/tattour/server/domain/sticker/provider/vo/ReadOrderSheetStickerInfo.java
  server/src/main/java/org/tattour/server/domain/sticker/repository/StickerImageRepository.java
  server/src/main/java/org/tattour/server/domain/sticker/repository/StickerRepository.java
  server/src/main/java/org/tattour/server/domain/sticker/repository/StickerStyleRepository.java
  server/src/main/java/org/tattour/server/domain/sticker/repository/StickerThemeRepository.java
  server/src/main/java/org/tattour/server/domain/sticker/service/StickerService.java
  server/src/main/java/org/tattour/server/domain/sticker/service/impl/StickerServiceImpl.java
  server/src/main/java/org/tattour/server/domain/style/domain/Style.java
  server/src/main/java/org/tattour/server/domain/style/provider/StyleProvider.java
  server/src/main/java/org/tattour/server/domain/style/provider/impl/StyleProviderImpl.java
  server/src/main/java/org/tattour/server/domain/style/repository/StyleRepository.java
  server/src/main/java/org/tattour/server/domain/theme/domain/Theme.java
  server/src/main/java/org/tattour/server/domain/theme/provider/ThemeProvider.java
  server/src/main/java/org/tattour/server/domain/theme/provider/impl/ThemeProviderImpl.java
  server/src/main/java/org/tattour/server/domain/theme/repository/ThemeRepository.java
  server/src/main/java/org/tattour/server/domain/user/controller/UserController.java
Labels: REFACTOR, 🐱서린

#122 #57 [REFACTOR] 결제 정보 불러오기 API 리팩토링
  .github/workflows/ci.yml
  .github/workflows/cicd.yml
  server/src/main/java/org/tattour/server/ServerApplication.java
  server/src/main/java/org/tattour/server/domain/order/controller/dto/response/GetOrderSheetRes.java
  server/src/main/java/org/tattour/server/domain/order/provider/dto/response/GetOrderAmountRes.java
  server/src/main/java/org/tattour/server/domain/order/provider/impl/OrderProviderImpl.java
  server/src/main/java/org/tattour/server/domain/user/provider/UserProvider.java
  server/src/main/java/org/tattour/server/domain/user/provider/impl/UserProviderImpl.java
  server/src/main/java/org/tattour/server/domain/user/provider/vo/UserProfileInfo.java
  server/src/main/java/org/tattour/server/global/util/EntityDtoMapper.java
Labels: REFACTOR

#123 #119 [FEAT] Magazine 도메인, 조회 api 추가
  server/src/main/java/org/tattour/server/domain/magazine/controller/MagazineController.java
  server/src/main/java/org/tattour/server/domain/magazine/controller/dto/response/GetMagazineListRes.java
  server/src/main/java/org/tattour/server/domain/magazine/controller/dto/response/GetMagazineRes.java
  server/src/main/java/org/tattour/server/domain/magazine/controller/dto/response/GetMagazineUrlRes.java
  server/src/main/java/org/tattour/server/domain/magazine/domain/Magazine.java
  server/src/main/java/org/tattour/server/domain/magazine/exception/NotFoundMagazineException.java
  server/src/main/java/org/tattour/server/domain/magazine/facade/MagazineFacade.java
  server/src/main/java/org/tattour/server/domain/magazine/facade/dto/response/ReadMagazineListRes.java
  server/src/main/java/org/tattour/server/domain/magazine/facade/dto/response/ReadMagazineRes.java
  server/src/main/java/org/tattour/server/domain/magazine/facade/dto/response/ReadMagazineUrlRes.java
  server/src/main/java/org/tattour/server/domain/magazine/facade/impl/MagazineFacadeImpl.java
  server/src/main/java/org/tattour/server/domain/magazine/provider/MagazineProvider.java
  server/src/main/java/org/tattour/server/domain/magazine/provider/impl/MagazineProviderImpl.java
  server/src/main/java/org/tattour/server/domain/magazine/repository/MagazineRepository.java
  server/src/main/java/org/tattour/server/domain/magazine/repository/impl/MagazineRepositoryImpl.java
  server/src/main/java/org/tattour/server/domain/user/facade/impl/UserFacadeImpl.java
  server/src/main/java/org/tattour/server/global/dto/SuccessType.java
  server/src/main/java/org/tattour/server/global/exception/ErrorType.java
Labels: FEAT, 🐱서린

#124 #119 [REFACTOR, FEAT] Magazine title, content 추가 / query dsl 리팩
  server/build.gradle
  server/src/main/generated/org/tattour/server/global/util/EntityDtoMapperImpl.java
  server/src/main/java/org/tattour/server/domain/custom/facade/impl/CustomFacadeImpl.java
  server/src/main/java/org/tattour/server/domain/custom/provider/CustomProvider.java
  server/src/main/java/org/tattour/server/domain/custom/provider/impl/CustomProviderImpl.java
  server/src/main/java/org/tattour/server/domain/custom/repository/CustomImageRepository.java
  server/src/main/java/org/tattour/server/domain/custom/repository/CustomRepository.java
  server/src/main/java/org/tattour/server/domain/custom/repository/CustomStyleRepository.java
  server/src/main/java/org/tattour/server/domain/custom/repository/CustomThemeRepository.java
  server/src/main/java/org/tattour/server/domain/custom/repository/custom/CustomRepositoryCustom.java
  server/src/main/java/org/tattour/server/domain/custom/repository/impl/CustomRepositoryImpl.java
  server/src/main/java/org/tattour/server/domain/custom/service/impl/CustomImageServiceImpl.java
  server/src/main/java/org/tattour/server/domain/custom/service/impl/CustomServiceImpl.java
  server/src/main/java/org/tattour/server/domain/custom/service/impl/CustomStyleServiceImpl.java
  server/src/main/java/org/tattour/server/domain/custom/service/impl/CustomThemeServiceImpl.java
  server/src/main/java/org/tattour/server/domain/magazine/controller/dto/response/GetMagazineListRes.java
  server/src/main/java/org/tattour/server/domain/magazine/domain/Magazine.java
  server/src/main/java/org/tattour/server/domain/magazine/facade/MagazineFacade.java
  server/src/main/java/org/tattour/server/domain/magazine/facade/dto/response/ReadMagazineListRes.java
  server/src/main/java/org/tattour/server/domain/magazine/facade/dto/response/ReadMagazineRes.java
  server/src/main/java/org/tattour/server/domain/magazine/facade/impl/MagazineFacadeImpl.java
  server/src/main/java/org/tattour/server/domain/sticker/provider/impl/StickerProviderImpl.java
  server/src/main/java/org/tattour/server/domain/sticker/repository/StickerRepository.java
  server/src/main/java/org/tattour/server/domain/sticker/repository/custom/StickerRepositoryCustom.java
  server/src/main/java/org/tattour/server/domain/sticker/repository/impl/StickerRepositoryImpl.java
  server/src/main/java/org/tattour/server/global/config/QuerydslConfig.java
  server/src/main/java/org/tattour/server/global/exception/ControllerExceptionHandler.java
Labels: FEAT, REFACTOR, 🐱서린

#126 #57 [REFACTOR] admin api 사용시 user role 검사 로직 추가
  .gitignore
  server/src/main/java/org/tattour/server/domain/admin/controller/AdminController.java
  server/src/main/java/org/tattour/server/domain/admin/controller/dto/request/CancelPointChargeRequestReq.java
  server/src/main/java/org/tattour/server/domain/admin/controller/dto/request/ConfirmPointChargeRequestReq.java
  server/src/main/java/org/tattour/server/domain/custom/controller/CustomController.java
  server/src/main/java/org/tattour/server/domain/order/controller/OrderController.java
  server/src/main/java/org/tattour/server/domain/order/provider/vo/OrderAmountInfo.java
  server/src/main/java/org/tattour/server/domain/user/controller/UserController.java
  server/src/main/java/org/tattour/server/domain/user/controller/dto/request/PostPointChargeRequest.java
  server/src/main/java/org/tattour/server/domain/user/provider/UserProvider.java
  server/src/main/java/org/tattour/server/domain/user/provider/impl/UserProviderImpl.java
  server/src/main/java/org/tattour/server/global/config/WebConfig.java
  server/src/main/java/org/tattour/server/global/config/annotations/DivisibleBy.java
  server/src/main/java/org/tattour/server/global/config/annotations/UserId.java
  server/src/main/java/org/tattour/server/global/config/interceptors/UserRoleInterceptor.java
  server/src/main/java/org/tattour/server/global/config/resolver/UserIdResolver.java
  server/src/main/java/org/tattour/server/global/exception/ErrorType.java
  server/src/main/java/org/tattour/server/global/util/validator/DivisibleByValidator.java
  server/src/main/java/org/tattour/server/infra/sms/controller/SmsController.java
  server/src/main/resources/logback-spring.xml
Labels: REFACTOR

#127 #119 [FIX] custom update error 수정
  server/src/main/java/org/tattour/server/domain/custom/facade/impl/CustomFacadeImpl.java
Labels: FIX, 🐱서린

#128 #119 [FIX] custom Read Res price 추가
  server/src/main/java/org/tattour/server/domain/custom/controller/dto/response/PatchCustomRes.java
  server/src/main/java/org/tattour/server/domain/custom/facade/dto/response/ReadCustomRes.java
  server/src/main/java/org/tattour/server/domain/custom/facade/impl/CustomFacadeImpl.java
Labels: FIX, 🐱서린
